services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "C:/Users/pakas/aqi-instance:/aqi-app/instance"
    command: sh -c "python init_db.py && python app.py"